### ISSUE TITLE
Consider providing an AUR package

### ISSUE THREAD

**Issue by coxackie** [avargas05/wacom-settings#1]
Many thanks for this. Looks very cool. Why not make an AUR package, given that you are anyway using it on arch?

**Comment by avargas05** [comment]
I have a PKGBUILD file that clones and builds it from the git repo. I just haven't figured out how to submit a package to AUR yet.

**Comment by coxackie** [comment]
It's all here:
https://wiki.archlinux.org/title/AUR_submission_guidelines
Pretty straightforward. 😁

**Comment by otreblan** [comment]
https://aur.archlinux.org/packages/wacom-settings-git/

**Comment by coxackie** [comment]
well done - closing, maybe add to the README.
